'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.34209
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("PowerPointAddIn1.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property CreateNewPng() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CreateNewPng", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property FindEmptyPng() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FindEmptyPng", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Struggle with updating an old slide instead of pasting a new one just becuase it is defined in all of your Custom Shows? now you can just repleace an old slide with a new one in all of your Custom Shows with a single click..
        '''</summary>
        Friend ReadOnly Property FirstInstall_Feature_SwapSlides_Desc() As String
            Get
                Return ResourceManager.GetString("FirstInstall_Feature_SwapSlides_Desc", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Swap 2 slides in all custom shows.
        '''</summary>
        Friend ReadOnly Property FirstInstall_Feature_SwapSlides_Title() As String
            Get
                Return ResourceManager.GetString("FirstInstall_Feature_SwapSlides_Title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please select 2 slides to be swapped..
        '''</summary>
        Friend ReadOnly Property Form_SwapSlides_BadSelection_ErrMsg() As String
            Get
                Return ResourceManager.GetString("Form_SwapSlides_BadSelection_ErrMsg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Successfully updated {{1}} custom slideshows..
        '''</summary>
        Friend ReadOnly Property Form_SwapSlides_Summary_Msg() As String
            Get
                Return ResourceManager.GetString("Form_SwapSlides_Summary_Msg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No custom slideshows were found or changed..
        '''</summary>
        Friend ReadOnly Property Form_SwapSlides_Summary_NoChange_Msg() As String
            Get
                Return ResourceManager.GetString("Form_SwapSlides_Summary_NoChange_Msg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Summary.
        '''</summary>
        Friend ReadOnly Property Form_SwapSlides_Summary_TItle() As String
            Get
                Return ResourceManager.GetString("Form_SwapSlides_Summary_TItle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Swap Slides....
        '''</summary>
        Friend ReadOnly Property Ribbon_CustomShows_SwapSlides_Button() As String
            Get
                Return ResourceManager.GetString("Ribbon_CustomShows_SwapSlides_Button", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property SwapSlidesArrow() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SwapSlidesArrow", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property SwapSlidesPng() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SwapSlidesPng", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
